### ISSUE TITLE
Wide-window angular spectrum method for diffractionpropagation in far and near field

### ISSUE THREAD

**Issue by kaanaksit** [kaanaksit/odak#12]
According to this [paper](https://doi.org/10.1364/OL.37.004943), although bandlimited angular spectrum method is valid for a wider propagation range compared to angular spectrum method, the accuracy of bandlimited angular spectrum method would decrease when the propagation distance is larger than 40 times the wavelength. The same paper explains the reasoning as follows: the band limits of a filter that avoids the aliasing is chosen according to the propagation distance of a beam, and in the large distances, the chosen limits are degrading the accuracy of the calculation. With respect to strict solution, this paper claims a superior accuracy, replicating it would be helpful in the long run.

**Comment by kunguz** [comment]
The steps required to complete this work is as follows:

- [ ] Fork this repository, and use the fork as a base to do your modifications.
- [ ] Create and implement a new definition called `wide_window_angular_spectrum` inside `odak.wave.classical` that can be found in [here](https://github.com/kunguz/odak/blob/master/odak/wave/classical.py). If you go through this script, you will see that there are many other definitions like `rayleigh_sommerfeld` or `angular_spectrum`. They can be inspirational for the implementation.
- [ ] Add an if statement with the keyword `Wide-window Angular Spectrum`, just like the one below to `propagate_beam` within [the same script](https://github.com/kunguz/odak/blob/master/odak/wave/classical.py).
https://github.com/kunguz/odak/blob/8d3237478e7b7d22877e2f26a41c7cba9b3babc5/odak/wave/classical.py#L37
- [ ] By using the [test script](https://github.com/kunguz/odak/blob/master/test/test_beam_propagation.py), one can experiment if this new method is operating as it should with the new keyword `Wide-window Angular Spectrum` in this line:
https://github.com/kunguz/odak/blob/8d3237478e7b7d22877e2f26a41c7cba9b3babc5/test/test_beam_propagation.py#L12
 You can also visualize the outcome by removing the commenting from those lines within the same test script:
https://github.com/kunguz/odak/blob/8d3237478e7b7d22877e2f26a41c7cba9b3babc5/test/test_beam_propagation.py#L36-L43
- [ ] Once you are confident with the new definition, start a pull request so that your fork can be merged with `Odak`.

Remember that I add each contributors name to [THANKS.txt](https://github.com/kunguz/odak/blob/master/THANKS.txt) and to the bibliography that can be found in [odak.bib](https://github.com/kunguz/odak/blob/master/citations/odak.bib) as well. So that when this library gets cited, you get your academic credit for it :)
